package io.mateu.erp.model.product.hotel;

public enum LinearFareKey {

    LODGING, MEAL, INDIVIDUALUSE, THIRDPAX, FOURTHPAX, FIFTHPAX, SIXTHPAX, FIRSTCHILD, SECONDCHILD, THIRDCHILD, FOURTHCHILD, FIFTHCHILD, FIRSTINFANT, PAX, SECONDINFANT

}
