
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package travel.caval._20091127.hotelbooking;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-01T19:27:17.548+02:00
 * Generated source version: 3.1.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "HotelBookingService",
                      portName = "HotelBookingServicePort",
                      targetNamespace = "http://caval.travel/20091127/hotelBooking",
                      wsdlLocation = "wsdls/caval/HotelBookingService.wsdl",
                      endpointInterface = "travel.caval._20091127.hotelbooking.HotelBookingService")
                      
public class HotelBookingServicePortImpl implements HotelBookingService {

    private static final Logger LOG = Logger.getLogger(HotelBookingServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see travel.caval._20091127.hotelbooking.HotelBookingService#getAvailableHotels(travel.caval._20091127.hotelbooking.CavalHotelAvailabilityRQ rq)*
     */
    public travel.caval._20091127.hotelbooking.CavalHotelAvailabilityRS getAvailableHotels(travel.caval._20091127.hotelbooking.CavalHotelAvailabilityRQ rq) { 
        LOG.info("Executing operation getAvailableHotels");
        System.out.println(rq);
        try {
            travel.caval._20091127.hotelbooking.CavalHotelAvailabilityRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see travel.caval._20091127.hotelbooking.HotelBookingService#getDetailedValuation(travel.caval._20091127.hotelbooking.CavalHotelBookingValuationRQ rq)*
     */
    public travel.caval._20091127.hotelbooking.CavalHotelBookingValuationRS getDetailedValuation(travel.caval._20091127.hotelbooking.CavalHotelBookingValuationRQ rq) { 
        LOG.info("Executing operation getDetailedValuation");
        System.out.println(rq);
        try {
            travel.caval._20091127.hotelbooking.CavalHotelBookingValuationRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see travel.caval._20091127.hotelbooking.HotelBookingService#getOffersList(travel.caval._20091127.hotelbooking.CavalGetOffersListRQ rq)*
     */
    public travel.caval._20091127.hotelbooking.CavalGetOffersListRS getOffersList(travel.caval._20091127.hotelbooking.CavalGetOffersListRQ rq) { 
        LOG.info("Executing operation getOffersList");
        System.out.println(rq);
        try {
            travel.caval._20091127.hotelbooking.CavalGetOffersListRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see travel.caval._20091127.hotelbooking.HotelBookingService#confirmHotelBooking(travel.caval._20091127.hotelbooking.CavalHotelBookingConfirmRQ rq)*
     */
    public travel.caval._20091127.hotelbooking.CavalHotelBookingConfirmRS confirmHotelBooking(travel.caval._20091127.hotelbooking.CavalHotelBookingConfirmRQ rq) { 
        LOG.info("Executing operation confirmHotelBooking");
        System.out.println(rq);
        try {
            travel.caval._20091127.hotelbooking.CavalHotelBookingConfirmRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see travel.caval._20091127.hotelbooking.HotelBookingService#getListOfBoardTypes(travel.caval._20091127.hotelbooking.CavalGetListOfBoardTypesRQ rq)*
     */
    public travel.caval._20091127.hotelbooking.CavalGetListOfBoardTypesRS getListOfBoardTypes(travel.caval._20091127.hotelbooking.CavalGetListOfBoardTypesRQ rq) { 
        LOG.info("Executing operation getListOfBoardTypes");
        System.out.println(rq);
        try {
            travel.caval._20091127.hotelbooking.CavalGetListOfBoardTypesRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see travel.caval._20091127.hotelbooking.HotelBookingService#getEstablishmentDataSheets(travel.caval._20091127.hotelbooking.CavalGetEstablishmentDataSheetsRQ rq)*
     */
    public travel.caval._20091127.hotelbooking.CavalGetEstablishmentDataSheetsRS getEstablishmentDataSheets(travel.caval._20091127.hotelbooking.CavalGetEstablishmentDataSheetsRQ rq) { 
        LOG.info("Executing operation getEstablishmentDataSheets");
        System.out.println(rq);
        try {
            travel.caval._20091127.hotelbooking.CavalGetEstablishmentDataSheetsRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see travel.caval._20091127.hotelbooking.HotelBookingService#notifyHotelBookings(travel.caval._20091127.hotelbooking.CavalHotelBookingNotificationRQ rq)*
     */
    public travel.caval._20091127.hotelbooking.CavalHotelBookingNotificationRS notifyHotelBookings(travel.caval._20091127.hotelbooking.CavalHotelBookingNotificationRQ rq) { 
        LOG.info("Executing operation notifyHotelBookings");
        System.out.println(rq);
        try {
            travel.caval._20091127.hotelbooking.CavalHotelBookingNotificationRS _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
