
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package io.mateu.common.traductores.ota.in;

import com.xmltravelgate.schemas.hub._2012._06.*;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-23T16:26:24.454+01:00
 * Generated source version: 3.2.0
 * 
 */

@WebService(
                      serviceName = "Hotel",
                      portName = "InsecureHttpPort",
                      targetNamespace = "http://schemas.xmltravelgate.com/hub/2012/06",
                      wsdlLocation = "caval/HotelBookingService.wsdl",
                      endpointInterface = "com.xmltravelgate.schemas.hub._2012._06.IServiceHotel")

public class HotelPortImpl implements IServiceHotel {

    private static final Logger LOG = Logger.getLogger(HotelPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.xmltravelgate.schemas.hub._2012._06.IServiceHotel#modifyValuation(com.xmltravelgate.schemas.hub._2012._06.ModifyValuation parameters)*
     */
    public ModifyValuationResponse modifyValuation(ModifyValuation parameters) {
        LOG.info("Executing operation modifyValuation");
        System.out.println(parameters);
        try {
            ModifyValuationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xmltravelgate.schemas.hub._2012._06.IServiceHotel#modifyReservation(com.xmltravelgate.schemas.hub._2012._06.ModifyReservation parameters)*
     */
    public ModifyReservationResponse modifyReservation(ModifyReservation parameters) {
        LOG.info("Executing operation modifyReservation");
        System.out.println(parameters);
        try {
            ModifyReservationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xmltravelgate.schemas.hub._2012._06.IServiceHotel#reservation(com.xmltravelgate.schemas.hub._2012._06.Reservation parameters)*
     */
    public ReservationResponse reservation(Reservation parameters) {
        LOG.info("Executing operation reservation");
        System.out.println(parameters);
        try {
            ReservationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xmltravelgate.schemas.hub._2012._06.IServiceHotel#reservationRead(com.xmltravelgate.schemas.hub._2012._06.ReservationRead parameters)*
     */
    public ReservationReadResponse reservationRead(ReservationRead parameters) {
        LOG.info("Executing operation reservationRead");
        System.out.println(parameters);
        try {
            ReservationReadResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xmltravelgate.schemas.hub._2012._06.IServiceHotel#reservationList(com.xmltravelgate.schemas.hub._2012._06.ReservationList parameters)*
     */
    public ReservationListResponse reservationList(ReservationList parameters) {
        LOG.info("Executing operation reservationList");
        System.out.println(parameters);
        try {
            ReservationListResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xmltravelgate.schemas.hub._2012._06.IServiceHotel#avail(com.xmltravelgate.schemas.hub._2012._06.Avail parameters)*
     */
    public AvailResponse avail(Avail parameters) {
        LOG.info("Executing operation avail");
        System.out.println(parameters);
        try {
            AvailResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xmltravelgate.schemas.hub._2012._06.IServiceHotel#valuation(com.xmltravelgate.schemas.hub._2012._06.Valuation parameters)*
     */
    public ValuationResponse valuation(Valuation parameters) {
        LOG.info("Executing operation valuation");
        System.out.println(parameters);
        try {
            ValuationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xmltravelgate.schemas.hub._2012._06.IServiceHotel#cancel(com.xmltravelgate.schemas.hub._2012._06.Cancel parameters)*
     */
    public CancelResponse cancel(Cancel parameters) {
        LOG.info("Executing operation cancel");
        System.out.println(parameters);
        try {
            CancelResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
