package travel.caval._20091127.commons;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-01T19:27:28.832+02:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "CommonsBookingService", 
                  wsdlLocation = "http://caval.travel/tech_specs/wsdls/CommonsBookingService.wsdl",
                  targetNamespace = "http://caval.travel/20091127/commons") 
public class CommonsBookingService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://caval.travel/20091127/commons", "CommonsBookingService");
    public final static QName CommonsBookingServicePort = new QName("http://caval.travel/20091127/commons", "CommonsBookingServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://caval.travel/tech_specs/wsdls/CommonsBookingService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommonsBookingService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://caval.travel/tech_specs/wsdls/CommonsBookingService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommonsBookingService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommonsBookingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonsBookingService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CommonsBookingService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CommonsBookingService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CommonsBookingService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CommonsBookingService
     */
    @WebEndpoint(name = "CommonsBookingServicePort")
    public CommonsBookingService getCommonsBookingServicePort() {
        return super.getPort(CommonsBookingServicePort, CommonsBookingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonsBookingService
     */
    @WebEndpoint(name = "CommonsBookingServicePort")
    public CommonsBookingService getCommonsBookingServicePort(WebServiceFeature... features) {
        return super.getPort(CommonsBookingServicePort, CommonsBookingService.class, features);
    }

}
