package travel.caval._20091127.commons;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-01T19:27:28.824+02:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://caval.travel/20091127/commons", name = "CommonsBookingService")
@XmlSeeAlso({ObjectFactory.class})
public interface CommonsBookingService {

    @WebMethod
    @RequestWrapper(localName = "getBooking", targetNamespace = "http://caval.travel/20091127/commons", className = "travel.caval._20091127.commons.GetBooking")
    @ResponseWrapper(localName = "getBookingResponse", targetNamespace = "http://caval.travel/20091127/commons", className = "travel.caval._20091127.commons.GetBookingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public travel.caval._20091127.commons.CavalGetBookingRS getBooking(
        @WebParam(name = "rq", targetNamespace = "")
        travel.caval._20091127.commons.CavalGetBookingRQ rq
    );

    @WebMethod
    @RequestWrapper(localName = "cancelBooking", targetNamespace = "http://caval.travel/20091127/commons", className = "travel.caval._20091127.commons.CancelBooking")
    @ResponseWrapper(localName = "cancelBookingResponse", targetNamespace = "http://caval.travel/20091127/commons", className = "travel.caval._20091127.commons.CancelBookingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public travel.caval._20091127.commons.CavalCancelBookingRS cancelBooking(
        @WebParam(name = "rq", targetNamespace = "")
        travel.caval._20091127.commons.CavalCancelBookingRQ rq
    );

    @WebMethod
    @RequestWrapper(localName = "getListOfBookings", targetNamespace = "http://caval.travel/20091127/commons", className = "travel.caval._20091127.commons.GetListOfBookings")
    @ResponseWrapper(localName = "getListOfBookingsResponse", targetNamespace = "http://caval.travel/20091127/commons", className = "travel.caval._20091127.commons.GetListOfBookingsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public travel.caval._20091127.commons.CavalGetListOfBookingsRS getListOfBookings(
        @WebParam(name = "rq", targetNamespace = "")
        travel.caval._20091127.commons.CavalGetListOfBookingsRQ rq
    );

    @WebMethod
    @RequestWrapper(localName = "getWholeSupportedMap", targetNamespace = "http://caval.travel/20091127/commons", className = "travel.caval._20091127.commons.GetWholeSupportedMap")
    @ResponseWrapper(localName = "getWholeSupportedMapResponse", targetNamespace = "http://caval.travel/20091127/commons", className = "travel.caval._20091127.commons.GetWholeSupportedMapResponse")
    @WebResult(name = "return", targetNamespace = "")
    public travel.caval._20091127.commons.CavalGetWholeSupportedMapRS getWholeSupportedMap(
        @WebParam(name = "rq", targetNamespace = "")
        travel.caval._20091127.commons.CavalGetWholeSupportedMapRQ rq
    );
}
