
package travel.caval._20091127.commons;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-01T19:27:28.830+02:00
 * Generated source version: 3.1.7
 * 
 */
 
public class CommonsBookingService_CommonsBookingServicePort_Server{

    protected CommonsBookingService_CommonsBookingServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CommonsBookingServicePortImpl();
        String address = "http://live.viajesurbis.com/serveis/caval/20091127/soap/CommonsBookingService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CommonsBookingService_CommonsBookingServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
